Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -36,11 +36,43 @@ steps:
         apt-get update
         apt-get install jq -y
         #obtener el qualitygate usando el API
-        responce =$(curl-s -u 2021fdd9704fb6d5378fcf9e817a873ee027bc46: https://sonarcloud.io/api/qualitygates/project_status?projectKey=gt0593sonarcloud_basic-nodejs-app) 
-        echo "$(curl-s -u 2021fdd9704fb6d5378fcf9e817a873ee027bc46: https://sonarcloud.io/api/qualitygates/project_status?projectKey=gt0593sonarcloud_basic-nodejs-app"
+        responce =$(curl -s -u 2021fdd9704fb6d5378fcf9e817a873ee027bc46: https://sonarcloud.io/api/qualitygates/project_status?projectKey=gt0593sonarcloud_basic-nodejs-app) 
+        echo "$(curl -s -u 2021fdd9704fb6d5378fcf9e817a873ee027bc46: https://sonarcloud.io/api/qualitygates/project_status?projectKey=gt0593sonarcloud_basic-nodejs-app"
         status =$(echo $response | jq -r '.projectStatus.status')
         echo "Chequeo de SonarCLoud = $status"
-        
+        if ["$status" == "ERROR"]
+        then
+          echo "Quality Gate Failed"
+        #  exit 1
+        fi
+        if ["$status" == "Ok"]
+        then
+          echo "Quality Gate Passed"
+        else
+          echo "Quality Gate unknow"
+        #  exit 2
+        fi
+    # Build the container image using definition on Dockerfile
+  - name: 'gcr.io/cloud-builders/docker'
+    args: ['build', '-t', 'us-central1-docker.pkg.dev/ecommerce-434317/ecommerce-art-front/ecommerce-art-front:$COMMIT_SHA', '.']
+
+    # Push the container image to Artifact Registry
+  - name: 'gcr.io/cloud-builders/docker'
+    args: ['push', 'us-central1-docker.pkg.dev/ecommerce-434317/ecommerce-art-front/ecommerce-art-front:$COMMIT_SHA']
+    # Deploy container image to Cloud Run
+  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
+    entrypoint: gcloud
+    args:
+    - 'run'
+    - 'deploy'
+    - 'ecommerce-art-front'
+    - '--image'
+    - 'us-central1-docker.pkg.dev/ecommerce-434317/ecommerce-art-front/ecommerce-art-front:$COMMIT_SHA'
+    - '--region'
+    - 'us-central1'
+images:
+  - 'us-central1-docker.pkg.dev/ecommerce-434317/ecommerce-art-front/ecommerce-art-front:$COMMIT_SHA'
+  
 options:
   logging: CLOUD_LOGGING_ONLY
 
